<table border="1" cellpadding="2" class="generalwindow">
	<tr>
		<td class="centertitle">管理员工具</td>
	</tr>
	<tr>
		<td style="<%=CssBgColor(TableContentBGC)%>">
			<table border="1" cellpadding="0" class="grid" style="text-align:center;">
				<tr style="cursor:pointer">
					<td style="width:14%" onclick="window.location='admin.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin.asp">管理首页</a></td>
					<td style="width:14%" onclick="window.location='admin_search.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_search.asp">搜索留言</a></td>
					<td style="width:15%" onclick="window.location='admin_advdel.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_advdel.asp">高级删除</a></td>
					<td style="width:15%" onclick="window.location='admin_setbulletin.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_setbulletin.asp">发布置顶公告</a></td>
					<td style="width:14%" onclick="window.location='admin_chpass.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_chpass.asp">修改密码</a></td>
					<td style="width:14%" onclick="window.location='admin_setinfo.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_setinfo.asp">修改版主资料</a></td>
					<td style="width:14%" onclick="window.location='admin_callgen.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_callgen.asp">生成调用代码</a></td>
				</tr>
				<tr style="cursor:pointer">
					<td style="width:14%" onclick="window.location='admin_config.asp?page=1'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_config.asp?page=1">留言本参数</a></td>
					<td style="width:14%" onclick="window.location='admin_ipconfig.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_ipconfig.asp">IP屏蔽策略</a></td>
					<td style="width:15%" onclick="window.location='admin_filter.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_filter.asp">内容过滤策略</a></td>
					<td style="width:15%" onclick="window.location='admin_floodconfig.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_floodconfig.asp">防灌水策略</a></td>
					<td style="width:14%" onclick="window.location='admin_stats.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_stats.asp">访问统计</a></td>
					<td style="width:14%" onclick="window.location='compact.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="compact.asp">压缩数据库</a></td>
					<td style="width:14%" onclick="window.location='admin_logoff.asp'" onmouseover="this.firstChild.style.textDecoration='underline'" onmouseout="this.firstChild.style.textDecoration=''"><a href="admin_logoff.asp">退出管理</a></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
