<div class="region admin-controls">
	<h3 class="title">管理员控制中心</h3>
	<div class="content flex-box">
		<ul>
			<li><a href="admin.asp">管理首页</a></li>
			<li><a href="admin_search.asp">搜索留言</a></li>
			<li><a href="admin_advdel.asp">高级删除</a></li>
			<li><a href="admin_setbulletin.asp">发布置顶公告</a></li>
			<li><a href="admin_chpass.asp">修改密码</a></li>
			<li><a href="admin_setinfo.asp">修改版主资料</a></li>
			<li><a href="admin_callgen.asp">生成调用代码</a></li>
			<li><a href="admin_config.asp?page=1">留言本参数</a></li>
			<li><a href="admin_ipconfig.asp">IP屏蔽策略</a></li>
			<li><a href="admin_filter.asp">内容过滤策略</a></li>
			<li><a href="admin_floodconfig.asp">防灌水策略</a></li>
			<li><a href="admin_stats.asp">访问统计</a></li>
			<li><a href="admin_compactdb.asp">压缩数据库</a></li>
			<li><a href="admin_logoff.asp">退出管理</a></li>
		</ul>
	</div>
</div>
